version = 0.1

[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "MohammadWaqasAziz"
github_repo = "Github_Actions_Aws_Sam"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::642078921032:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-Rghn2Tup8yS2"
cloudformation_execution_role = "arn:aws:iam::642078921032:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-hOPahESY2DJi"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-7v1etlsv3beu"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::642078921032:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-7J7FvlGK2Du8"
cloudformation_execution_role = "arn:aws:iam::642078921032:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-HqF6PZisLPdX"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-pqdvaimw5lu8"
image_repository = ""
region = "us-east-1"
